name: develop CI Pipeline

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'

      - name: Install dependencies
        run: yarn install

      - name: Run TypeScript Type Check
        run: yarn tsc --noEmit

      - name: Build Project
        run: yarn build

      - name: Lint Code
        run: yarn lint

      - name: Check Code Formatting
        run: yarn format-check

      - name: Execute Tests
        run: yarn test
